### ISSUE TITLE
Remove deprecated features

### ISSUE THREAD

**Issue by trevorld** [piecepackr/piecepackr#260]
Deprecated features to remove in a future release:

* [x] Using `pdffonts` instead of `{pdftools}` in `get_embedded_font()`

  + Deprecated in v1.13.1 (2023-03-23)
  + Install the suggested `{pdftools}` package

* [x] `animate_piece()`'s `annotate` argument unnamed

  + Deprecated in v1.10.3 (2022-03-23)
  + Either use it named or leave it omitted (and use its default)

* [x] `pp_cfg()$get_shadow_fn()`

  + Deprecated in v1.10.1 (2022-02-22)
  + Use `pp_cfg()$get_op_grob()` to get oblique projection **grob**

* [x] `pieceGrob()` and `grid.piece()`'s `use_pictureGrob` argument

  + Deprecated in v1.8.1 (2021-08-11)
  + Use `type = "picture"` instead

* [x] `pp_cfg()$i_unsuit`

  + Deprecated in v1.7.1 (2021-03-25)
  + Use `pp_cfg()$n_suits + 1L`

* [x] `pp_cfg()$cache_shadow`

  + Deprecated in v1.7.1 (2021-03-25)
  + Use `pp_cfg()$cache_op_fn`

**Comment by RishiKumarRay** [comment]
Do we have to remove pp_cfg()$cache_shadow and add this pp_cfg()$cache_op_fn?
