### ISSUE TITLE
{rayvertex} bindings giving worse renderings than before

### ISSUE THREAD

**Issue by trevorld** [piecepackr/piecepackr#306]
* Not to be confused with the now fixed regression in `{rayrender}` bindings #304
* The `{rayvertex}` example from the README seems buggy:

```r
library("piecepackr")
library("ppgames") # remotes::install_github("piecepackr/ppgames")
library("rayvertex", warn.conflicts = FALSE) # masks `rayrender::r_obj`
df <- ppgames::df_international_chess()
envir <- game_systems("dejavu3d", round=TRUE, pawn="joystick")
l <- pmap_piece(df, piece_mesh, trans=op_transform, envir = envir, scale = 0.98, res = 150, as_top="pawn_face")
table <- sphere_mesh(c(0, 0, -1e3), radius=1e3, material = material_list(diffuse="grey40"))
scene <- Reduce(rayvertex::add_shape, l, init=table)
rayvertex::rasterize_scene(scene, lookat = c(4.5, 4, 0), lookfrom=c(4.5, -16, 20),
                           light_info = directional_light(c(5, -7, 7), intensity = 2.5))

```

![rayvertex_bug](https://user-images.githubusercontent.com/2433259/198390500-a6d81d75-48e8-4ccc-b912-b4885bb8a77c.png)

**Comment by trevorld** [comment]
Bug reported upstream: https://github.com/tylermorganwall/rayvertex/issues/9

**Comment by trevorld** [comment]
* Should be fixed now with the development version of `{rayvertex}`: `remotes::install_github("tylermorganwall/rayvertex")`
* When the CRAN version gets updated bump the version number in our DESCRIPTION

**Comment by trevorld** [comment]
CRAN version finally got bumped to v0.7.9

**Comment by trevorld** [comment]
The `{rayvertex}` example from the README no longer produces a shadow effect (most noticeably on the joystick pawns) with `{rayvertex}` v0.7.9:

![rayvertex](https://github.com/piecepackr/piecepackr/assets/2433259/c238af8b-6245-425a-b750-78c1b1cbf9f0)

Probably shouldn't bump the version number yet until we get a `{rayvertex}` release and/or figure out how to update our code so we get a visual effect that is equal to or an improvement on `{rayvertex}` v0.3.3.

First issue raised upstream in `{rayvertex}`: https://github.com/tylermorganwall/rayvertex/issues/14

**Comment by tylermorganwall** [comment]
Both issues should be fixed in the latest commits

**Comment by trevorld** [comment]
Thanks!  I've installed the development version of `{rayvertex}` (v0.8.2) and I confirm that it fixes the issues in my `{rayvertex}` example.
