### ISSUE TITLE
`piece_mesh()` no longer works with `{rayvertex}` v0.10.3

### ISSUE THREAD

**Issue by trevorld** [piecepackr/piecepackr#339]
Prof. Ripley writes:

> Dear maintainer,
> 
> Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_piecepackr.html>.
> 
> Please correct before 2023-12-26 to safely retain your package on CRAN.
> 
> Do remember to look at the 'Additional issues'.
> 
> The CRAN Team

This appears to be due to a possible regression in `{rayvertex}`: https://github.com/tylermorganwall/rayvertex/issues/16

**Comment by tylermorganwall** [comment]
rayvertex has been updated on the CRAN

**Comment by trevorld** [comment]
> rayvertex has been updated on the CRAN

Thanks!  It looks like the "donttest" Additional issue has already disappeared from my CRAN check results page.

To be double safe I'll bump the required version number for `{rayvertex}` in the `DESCRIPTION` and release an updated version of `{piecepackr}` to CRAN soon (NB. CRAN submission is closed from Dec. 22 due to holiday break).  We'll eliminate the new #337 NOTE as well.
